services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_ML_BACKEND_URL=http://localhost:8001
      - REACT_APP_BACKEND_URL=http://localhost:8081
    depends_on:
      - ml-backend
      - backend

  ml-backend:
    build:
      context: ./ml-backend
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./ml-backend/artifacts:/app/artifacts
    command: uvicorn serve:create_app --factory --host 0.0.0.0 --port 8001 --reload

  backend:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_PORT=8081
    volumes:
      - ./logs:/logs 